{{- if and .Values.mariadb.enabled (not .Values.mariadb.auth.existingSecret)}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "yona.fullname" . }}-db-secret"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yona.mariadb.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $rootPassword := .Values.mariadb.auth.rootPassword | b64enc | quote }}
  MARIADB_ROOT_PASSWORD: {{ $rootPassword }}
  {{- $password := .Values.mariadb.auth.password | b64enc | quote }}
  MARIADB_PASSWORD: {{ $password }}
{{- end }}