{{- if .Values.mariadb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "yona.fullname" .}}-db"
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.mariadb.port }}
      targetPort: mariadb
      protocol: TCP
      name: mariadb
  selector:
    {{- include "yona.mariadb.selectorLabels" . | nindent 4 }}
{{- end}}    
