{{- if not .Values.yona.env.imap.existingSecret}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "yona.fullname" . }}-imap-secret"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yona.labels" . | nindent 4 }}
type: Opaque
data:
  YONA_IMAP_PASSWORD: {{ .Values.yona.env.imap.password | b64enc | quote }}
{{- end }}