{{- if not .Values.yona.env.smtp.existingSecret}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "yona.fullname" . }}-smtp-secret"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yona.labels" . | nindent 4 }}
type: Opaque
data:
  YONA_SMTP_PASSWORD: {{ .Values.yona.env.smtp.password | b64enc | quote }}
{{- end }}