{{- if not .Values.yona.socialLogin.google.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "yona.fullname" . }}-social-google-secret"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yona.labels" . | nindent 4 }}
type: Opaque
data:
  YONA_SOCIAL_LOGIN_GOOGLE_CLIENT_SECRET: {{ .Values.yona.socialLogin.google.clientSecret | b64enc | quote }}
{{- end }}